apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grade-submission-api
  template:
    metadata:
      labels:
        app: grade-submission-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: grade-submission-api
          image: ghcr.io/jumptotechschooldevops/k8s-ci-build:PLACEHOLDER
          ports:
            - containerPort: 3000
